# ─── 書本基本資料 ───────────────────────────
title      : "高階合成入門 | High-Level Synthesis Tutorial"
author     : "weiber"
logo       : _static/logo.png
copyright  : "© 2025 Wei-Po"

# ─── GitHub 連結 ───────────────────────────
repository:
  url    : https://github.com/weiber2002/HLS_tutorial
  branch : main

# ─── HTML 介面 ─────────────────────────────
html:
  favicon                : _static/favicon.ico     # 沒有可刪
  use_issues_button      : true
  use_repository_button  : true
  last_updated_fmt       : "%Y-%m-%d %H:%M"
  css:
    - _static/custom.css                       # 自訂樣式

  # ── 分析工具 (新版路徑) ──────────────────
  analytics:
    google_analytics_id : ""                   # 需要再填 UA-XXXX 或 GA4

  # ── Sphinx-book-theme 選項 ───────────────
  extra_footer: |
    <div style="text-align:center;font-size:0.9em">
      以 <a href="https://jupyterbook.org" target="_blank">Jupyter Book</a> 建立 ·
      最後更新 {{ last_updated }}
    </div>

  theme:
    name   : sphinx_book_theme
    options:
      home_page_in_navbar  : true
      repository_url       : https://github.com/weiber2002/HLS_tutorial
      repository_branch    : main
      path_to_docs         : ""                 # 放根目錄就留空
      use_fullscreen_button: false
      navigation_with_keys : true
      show_navbar_depth    : 2
      extra_navbar: |
        <a href="https://github.com/weiber2002/HLS_tutorial/issues" target="_blank">問題回報</a>
